services:
  pagueveloz.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=paguevelozdb;Port=5432;Database=db_pagueveloz_dev;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - paguevelozdb
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  paguevelozdb:
    container_name: paguevelozdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_pagueveloz_dev
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - pagueveloz_postgres_data:/var/lib/postgresql/data